### ISSUE TITLE
Create HTML or PDF version of QVC API documentation for use by PE users

### ISSUE THREAD

**Issue by RobWunderlich** [RobWunderlich/Qlikview-Components#1]
Personal Edition users can't open the QvcDocumentation.qvw. Generate an alternative documentation for them.

(This issue moved from Google issue #40)

**Comment by MattFryer** [comment]
Hi Rob
Could be worth asking Qlik to flag QVW as a demo so personal edition users can open it. It would save having to maintain 2 versions of the documentation. Although you might have to ask them to redo it every time you release a new version.

Regards
Matt

**Comment by RobWunderlich** [comment]
A good idea and coincidently in the works I expect to have QVC PE enabled in the next couple weeks. Then we can close this issue.

**Comment by RobWunderlich** [comment]
V10 will be PE enabled.
