### ISSUE TITLE
Replace obsolete @version doc tag with new @source tag

### ISSUE THREAD

**Issue by RobWunderlich** [RobWunderlich/Qlikview-Components#15]
When QVC was hosted in SVN, the @version $Id$ tag was used to track version number and source file location, In Git, version number of the source has no useful meaning, We still use the source file in the generated QvcDocumentation, Let's replace @version with a new @source tag to identify the source file and clarify the meaning of the tag.

**Comment by RobWunderlich** [comment]
Probably a better solution would be to have the build insert the @source file name, removing the requirement for manual entry.

**Comment by veglar** [comment]
I Agree. As long we get an idea of which release it is. Automatic generated tags are better than manual.

**Comment by MattFryer** [comment]
As the change log should be updated with any new functions and subs, it should indicate what release version it was introduced in.

**Comment by veglar** [comment]
Yes, smilar as it was automaticly even using svn
Sent using CloudMagic
On tor., feb. 19, 2015 at 11:56 AM, Matt Fryer <notifications@github.com> wrote:As the change log should be updated with any new functions and subs, it should indicate what release version it was introduced in.

**Comment by RobWunderlich** [comment]
All @version tags have been replaced
