### ISSUE TITLE
Remote include of qvs file

### ISSUE THREAD

**Issue by MattFryer** [RobWunderlich/Qlikview-Components#19]
It is possible to manually write an include statement to include a qvs file from a URL such as:
$(Include=http://www.qvcomponents.com/Qvc.qvs);
This would allow for users to always be using the latest version of QVC. However it could also mean that production applications could be effected by changes in a new release.

**Comment by philippfrenzel** [comment]
Actually you should take a look at versioning, so you can ensure that you decide when to upgrade;)

**Comment by MattFryer** [comment]
QVC already has the ability to check if a new version is available. This user has to perform the update manually. This would simply give the option for users to always be using the latest version without having to manually update.

**Comment by nate-untiedt** [comment]
This seems to work when I try it with QV 11.2 SR7:
$(Must_Include=https://github.com/nate-untiedt/Qlikview-Components/releases/download/v10.1/Qvc.qvs);

By adding a copy of the Qvc.qvs as a binary download file in releases going forward users would be able to at least tie their include to a specific release and make their qvw a little more portable/stable.

**Comment by RobWunderlich** [comment]
Delivered in V11
