### ISSUE TITLE
Incremental Reload: not correct where condictional for Oracle DB

### ISSUE THREAD

**Issue by pljluca** [RobWunderlich/Qlikview-Components#22]
I tried to use incremental reload to load a table from Oracle DB but the where condition on datetime generate an error ORA-01843.

I have set this code:
```
SET Qvc.Loader.v.QvdDirectory='..\QVD\';
LET Qvc.Loader.v.BaseValue = num(MakeDate(2000,01,01));
SET Qvc.Loader.v.DatabaseDatetimeMask = 'YYYY-MM-DD hh:mm:ss';
SET Qvc.Loader.v.StoreMaxModFieldValue = -1;
SET Qvc.Loader.v.Database = ORACLE;
SET Qvc.Loader.v.ModField.Type = 'Datetime';

CALL Qvc.IncrementalSetup ('TestTable', 'REFERENCES$LASTUPDATEDATE', 'ID'); 

[$(Qvc.Loader.v.Tablename)]:		// vTablename is set by the IncrementalSetup routine.
LOAD
	*
;
SQL SELECT *
FROM TestDB."TestTable"
WHERE $(Qvc.Loader.v.IncrementalExpression);
```

and the Log file give me this

```
SQL SELECT *
FROM TestDB."TestTable"
WHERE REFERENCES$LASTUPDATEDATE >= TIMESTAMP '2000-01-01 00:00:00'
Error: ErrorSource: OraOLEDB, ErrorMsg: ORA-01843: not a valid month
```
I test on query in Oracle DB and the correct query is 
```
SELECT *
FROM TestDB."TestTable"
WHERE REFERENCES$LASTUPDATEDATE >= '2000-01-01 00:00:00'
```

I think that the error is on row 132 in file Qvc_Incremental_Reload.qvs
```
LET Qvc.Loader.v.IncrementalExpression = '$(_vSqlModField) ' & $(_tempLoaderPredicate($(Qvc.Loader.v.BaseValue)));
```
Best Regards
Luca Jonathan Panetta

**Comment by RobWunderlich** [comment]
What version of Oracle server is this?

**Comment by pljluca** [comment]
Hi Rob,
sorry I forgot it, the Oracle version is 11.2.0.3.

At the moment I solved my problem by using
```
SET Qvc.Loader.v.Database = SQLSERVER;
```
Best Regards
Luca Jonathan Panetta

**Comment by RobWunderlich** [comment]
Is it possible that the datatype of REFERENCES$LASTUPDATEDATE is not TIMESTAMP, but CHAR?

-Rob

**Comment by pljluca** [comment]
I verified the query and yes, my colleague wrote data type of REFERENCES$LASTUPDATEDATE  as VARCHAR. 

Sorry I haven't check it before.
Thanks a lot for your support.

**Comment by MattFryer** [comment]
No worries, thanks for letting us know Luca!

-Matt
