### ISSUE TITLE
IncrementalSetup: error if QVD exists but it is empty

### ISSUE THREAD

**Issue by pljluca** [RobWunderlich/Qlikview-Components#24]
Hello, 
I have a table that sometimes is empty and I want to do an incremental load, I do
```
// The directory for the QVD file
SET Qvc.Loader.v.QvdDirectory = '..\QVD';

// How far back to load if First Load 
LET Qvc.Loader.v.BaseValue = num(MakeDate(2000, 1, 1));

// Datetime literal format for Excel - Shipper exercise
SET Qvc.Loader.v.DatabaseDatetimeMask = 'YYYY-MM-DD hh:mm:ss'; //'MM/DD/YYYY';

// Will the max Modfield value be stored with the QVD?
// The recommended value is True. This will greatly speed up subsequent loads. 
SET Qvc.Loader.v.StoreMaxModFieldValue = -1;

/*	Database product where tables will be loaded from.
	Possible values are SQLSERVER | ORACLE | SFDC.
	Default is SQLSERVER. For non-database files, use SQLSERVER.
*/
SET Qvc.Loader.v.Database = ORACLE;
SET Qvc.Loader.v.ModField.Type = 'Datetime';

LET vs_ForceFullReload = 0;
CALL Qvc.IncrementalSetup ('MyTable', 'REFERENCES$LASTUPDATEDATE', 'PK', $(vs_ForceFullReload)); 

[$(Qvc.Loader.v.Tablename)]:
LOAD
	PK
	,REFERENCES$LASTUPDATEDATE
;
SQL SELECT
	*
FROM MyTable
WHERE isDeleted <> 'true'
$(Qvc.Loader.v.IncrementalExpression);
```

but I receive an error from DB because the executed query is
```
SELECT
	*
FROM MyTable
WHERE isDeleted <> 'true'
and REFERENCES$LASTUPDATEDATE >= TIMESTAMP ''
```

I tried to solve the problem and I seen that Qvc.Loader.v.IncrementalExpression generate this problem because in Qvc_Incremental_Reload.qvs row 124
```
SET Qvc.Loader.v.IncrementalFloor = $(_vDate.Max);	// Save copy for user defined custom where expression
```
not is considered the case where QVD exists but it is empty.

I solve this problem with this code 
```
IF (Len(Trim('$(_vDate.Max)')) = 0) then
	LET Qvc.Loader.v.IncrementalFloor = '$(Qvc.Loader.v.BaseValue)';	// Save copy for user defined custom where expression
ELSE
	LET Qvc.Loader.v.IncrementalFloor = '$(_vDate.Max)';	// Save copy for user defined custom where expression
ENDIF

// Create a where predicate
LET Qvc.Loader.v.IncrementalExpression = '$(_vSqlModField) ' & $(_tempLoaderPredicate($(Qvc.Loader.v.IncrementalFloor)));	
```

In the last row I replaced $(_tempLoaderPredicate($(***_vDate.Max***))) with $(_tempLoaderPredicate($(***Qvc.Loader.v.IncrementalFloor***)))

Other thing, the Qvc.Loader.v.IncrementalFloor variable is "Save copy for user defined custom where expression" but in the documentation it is not present in the output funcion parameter.

**Comment by MattFryer** [comment]
Hi Luca
Thanks for the lengthy explanation and proposed solution. They were really helpful in understanding the issue. I've gone with with a slightly different solution which I think is more robust. Qvc.IncrementalSetup already tests if the QVD exists and if it doesn't then it essentially treats it as if it is performing a full reload (line 100). I have added to this a check that the QVD not only exists but that it contains at least one record using the QvdNoOfRecords() function. Doing it this way means it should still work even if the user forgets to set Qvc.Loader.v.BaseValue. 

Regards
Matt
