### ISSUE TITLE
Add Year-Quarter field to Calendar

### ISSUE THREAD

**Issue by RobWunderlich** [RobWunderlich/Qlikview-Components#25]
Add a Year-Quarter field to calendar. Need to ensure we give people enough heads-up to avoid conflict with any field they added.

**Comment by MattFryer** [comment]
I've been thinking about this. I've not looked at the real detail yet, but on the surface it seems that the extended fields are held in CalendarExtFields.qvs and end up in a variable _qvctemp.v.IncludeExtension which is used in the LOAD for the calendar to add the extra user defined fields. If this is the case, can we not simply use substringcount to see if "Year-Quarter" exists in the variable before adding a Year-Quarter field. In reality it might need to be a little more complex to ensure the field name exists more like "AS Year-Quarter," and handle all the possibilities but I'm sure we can work out the logic. 

This method could in theory be applied to any calendar fields and would essentially mean a user defined field in the script file would take priority.

The only other option I could think of was to set ErrorMode to 0, load the table, check if an error occurred and if so use trace to write a message telling the user to remove their own definition of "Year-Quarter" and then exit the script.

**Comment by RobWunderlich** [comment]
Sounds like a good solution. I think it's workable.


On Mar 19, 2015, at 11:22 AM, Matt Fryer <notifications@github.com> wrote:

I've been thinking about this. I've not looked at the real detail yet, but
on the surface it seems that the extended fields are held in
CalendarExtFields.qvs and end up in a variable _qvctemp.v.IncludeExtension
which is used in the LOAD for the calendar to add the extra user defined
fields. If this is the case, can we not simply use substringcount to see if
"Year-Quarter" exists in the variable before adding a Year-Quarter field.
In reality it might need to be a little more complex to ensure the field
name exists more like "AS Year-Quarter," and handle all the possibilities
but I'm sure we can work out the logic.

This method could in theory be applied to any calendar fields and would
essentially mean a user defined field in the script file would take
priority.

The only other option I could think of was to set ErrorMode to 0, load the
table, check if an error occurred and if so use trace to write a message
telling the user to remove their own definition of "Year-Quarter" and then
exit the script.

—
Reply to this email directly or view it on GitHub
<https://github.com/RobWunderlich/Qlikview-Components/issues/25#issuecomment-83700576>
.

**Comment by MattFryer** [comment]
I say we add the year quarter field to the next release using this method and see if we get any fall out. If not then we can add additional fields and even perform the same check for existing fields in a following release.
