### ISSUE TITLE
Lack of square brackets

### ISSUE THREAD

**Issue by pljluca** [RobWunderlich/Qlikview-Components#27]
Hello,

in my work with Qvc library I have a table name with spaces and I have some errors when I use Qvc.IncrementalStore.

I checked the function and in Qvc_Incremental_Reload.qvs to the rows
```
287: LOAD DISTINCT [$(_vPrimaryKey)] as [_qvctemp.PK_values] Resident $(_vTablename);
299: CONCATENATE ($(_vTablename))
300: LOAD * FROM $(_vQvdFile) (qvd)
322: STORE $(_vTablename) INTO $(_vQvdFile);
```
lack the square brackets.

Thanks a lot for you work.
Luca Jonathan Panetta

PS: How can I join to the project?

**Comment by RobWunderlich** [comment]
You can contribute to the project by forking the project, making changes and submitting a pull request. If you'd prefer to not go to that length, you can submit code on the forum or the issue tracker. But we do appreciate code as complete as possible. The coding guidelines can be found in the wiki in this project. use the forum if you have any questions. We welcome your contributions!
