### ISSUE TITLE
vSetYTD not working in Sense 

### ISSUE THREAD

**Issue by veglar** [RobWunderlich/Qlikview-Components#29]
I experience the Set and set modifier not to work properly  in Sense. Using the vSetYTD or vSetYTDModifier will ignore any selection done in the application. 
It will make a YTD for my selection ignoring any of my date selections. 

Removing the `{1<_Qvc.DummyField=$(_Qvc.Calendar.v.SelectedFieldList_)>}' SET did help solve the problem in my case. (Why do QVC use this set on a dummy field that does not exist?)

``` [%Verifikatdatum]=,[Dag]=,[Veckodag]=,[År]=,[Månad]=,[Kvartal]=,[_DateSerial]=,[_MonthSerial]=,[_QuarterSerial]=,[_WeekSerial]=,[År-Månad]=,
[_DateSerial] = {"<=$(=Max({1<_Qvc.DummyField=$(_Qvc.Calendar.v.SelectedFieldList_)>}[_DateSerial]))"},
[År] = {"$(=Max({1<_Qvc.DummyField=$(_Qvc.Calendar.v.SelectedFieldList_)>}[År]))"}
```

**Comment by RobWunderlich** [comment]
It's working for me in limited testing. Can you upload a qvf that demonstrates the problem?

The dummyField is just a method for avoiding syntax error from the leading comma.

**Comment by veglar** [comment]
I'm not able to provide the qvf, but I'll try to reproduce the issue for
you.

Den mandag 11. mai 2015 skrev RobWunderlich <notifications@github.com>
følgende:

**Comment by RobWunderlich** [comment]
Assumed fixed due to lack of activity. Please reopen if the problem remains.
