### ISSUE TITLE
Qvc_ExpandInterval Step Interval Parameter

### ISSUE THREAD

**Issue by ianperrin** [RobWunderlich/Qlikview-Components#37]
Hi Rob

Would you be able to provide more information on how to use the Qvc_ExpandInterval function - specifically the use of the optional 5th "step interval" parameter?

We're trying to create Hourly (or even half hourly) intervals for a set of session data and were hoping to use your function but can't seem to get it to work with the following call

```
Session:
LOAD * INLINE [
    SessionID, SessionStartDateTime, SessionEndDateTime, Value
    1, 01/02/2015 10:14:00, 01/02/2015 11:44:00, a
    2, 01/02/2015 09:35:00, 01/02/2015 12:00:00, b
    3, 01/02/2015 16:20:00, 01/03/2015 01:10:00, c
];

// Snapshot for illustration purposes
QUALIFY *;
SessionRaw:
LOAD * Resident Session;
UNQUALIFY *;

CALL Qvc.ExpandInterval ('Session', 'SessionStartDateTime', 'SessionEndDateTime', '', 'HOUR')
```

Any ideas what we're doing wrong?

Thanks

Ian

**Comment by RobWunderlich** [comment]
Hi Ian,

The step interval parameter is not yet available. It should be commented
out in the 10.2 version. What version are you using?

-Rob

**Comment by ianperrin** [comment]
Ah okay, having looked at the QVS script I can see the comments vStep code. Is there a solution on the near horizon or this just a placeholder for an idea?
