### ISSUE TITLE
Additional Point in Time Reporting variables

### ISSUE THREAD

**Issue by M2r4Miller** [RobWunderlich/Qlikview-Components#38]
Rob,

Excellent toolkit, thank you!
This isn't an "issue" per se...
I added new Set Variable definitions for PITR requirements we have here and would like to share them with you. The expressions include:

$(_fieldPrefix)vSetPreviousFULLMonth = Returns the entire previous month.
$(_fieldPrefix)vSetPreviousFULLMonthN = Returns the entire month "N" months back - this is parameterized.
$(_fieldPrefix)vSetRollingN - Parameterized, similar to your vSetRolling12, but with the parameter can give rolling 3 months, 6 months, 4 months, etc.

I also made a slight change to Qvc.Calendar - basically I use Dual() for the month, which allows a list box of months to be in the proper order for fiscal or calendar years.

How would you like me to submit these changes to you for your review?

Thanks again for an excellent toolkit!

**Comment by RobWunderlich** [comment]
Great! If you've forked the project, just submit a pull request. Otherwise you can zip up the changes and post here

**Comment by M2r4Miller** [comment]
I think I have attached the file, not sure since I can't see the file after dragging and dropping or selecting.
To be honest, GitHub and open source projects are a new concept for me. I'll have to read up on this since I have no idea what you mean <hangs head in shame>

**Comment by gardnmi** [comment]
Hey M2r4Miller, 

These appear to be great changes.  Below is a good video link on Forking and Pulling.

https://www.youtube.com/watch?v=YTbRzhQju4c

**Comment by M2r4Miller** [comment]
Thanks! I'll watch it soon - I did fork the project and add the changes to QVC_Calendar.qvs. Not sure what else to do now, hopefully things will be clearer after I watch the video. :)

**Comment by RobWunderlich** [comment]
Sorry for the delay in picking up your changes.,I've been swamped! I hope
to get to it next week.

On Mar 2, 2016, at 12:14 PM, M2r4Miller <notifications@github.com> wrote:

Thanks! I'll watch it soon - I did fork the project and add the changes to
QVC_Calendar.qvs. Not sure what else to do now, hopefully things will be
clearer after I watch the video. :)

—
Reply to this email directly or view it on GitHub
<https://github.com/RobWunderlich/Qlikview-Components/issues/38#issuecomment-191406934>
.

**Comment by RobWunderlich** [comment]
I'd like to incorporate these changes. I don't see a pull request or an attached file. Can you try attaching the file again?

**Comment by M2r4Miller** [comment]
I think I finally did this correctly - at least I now see an open pull request!
Sorry for the delay, I didn't realize you had a question out here for me from May.
BTW, it was a pleasure meeting you in Florida at Qonnections!

**Comment by RobWunderlich** [comment]
Pull request integrated in V11
