### ISSUE TITLE
DbExtract doesn't support Revision update type

### ISSUE THREAD

**Issue by nixnut** [RobWunderlich/Qlikview-Components#40]
The DbExtract routine is missing a few bits to support update type Revision:

LET _qvctemp.den.updateFieldType = peek('UpdateFieldType', $(_qvctemp.den._listIndex), '$(_qvctemp.den.extractList)');

IF len('$(_qvctemp.den.updateFieldType)') > 0 THEN 
	SET Qvc.Loader.v.ModField.Type = $(_qvctemp.den.updateFieldType);
ENDIF

**Comment by RobWunderlich** [comment]
Duplicate of #47
