### ISSUE TITLE
Recommended value of Qvc.Loader.v.StoreMaxModFieldValue does not match the value set by default

### ISSUE THREAD

**Issue by nixnut** [RobWunderlich/Qlikview-Components#42]
According to the comment below the recommended value is -1, but the code set the value to 0.

 // If true, a new field "Qvc.MaxModFieldValue" will be created in the QVD. 
 // This will greatly increase the speed of subsequent delta loads. 
 // True (-1) is the recommended value. 
SET Qvc.Loader.v.StoreMaxModFieldValue = 0;

**Comment by RobWunderlich** [comment]
It's recommended to be -1, but the default is 0. The thinking is that we should not introduce any new data into a QVD without the user being explicit.
