### ISSUE TITLE
Request option for incremental loading without primary key

### ISSUE THREAD

**Issue by nixnut** [RobWunderlich/Qlikview-Components#43]
I ran into a case where I want to do incremental reloading based on a timestamp only, i.e. give me all the records newer than the max timestamp of the previous load. Several records may have the exact same timestamp. Using the timestamp as primary key as well as modification field therefore doesn't work.
  
I propose a conditional WHERE clause based on the existence of the primary key in the arguments passed to the UpdateQvd routine

WHEN Len('$(_vPrimaryKey)')>0 SET _qvctemp.vWHERE = WHERE NOT exists($(_qvctemp.ExistsExpr));

 REM If incremental reload, load previous data and concatenate to data just read.;
 IF $(_vQvdExists) THEN
 // Concatenate is required if adding fields
 	CONCATENATE ([$(_vTablename)])
 	LOAD * FROM [$(_vQvdFile)] (qvd)
	$(_qvctemp.vWHERE)

**Comment by RobWunderlich** [comment]
I think this case is already covered by setting?
SET Qvc.Loader.v.KeyFieldIsUnique=0;

**Comment by nixnut** [comment]
PEBKAC. Messing up upper and lower case etc. Perhaps this change is acceptable so fools like myself can be a little careless:

LET _qvctemp.den.uniqueKey = ApplyMap('_qvctemp.TFMap', Upper(peek('UniqueKey', $(_qvctemp.den._listIndex), '$(_qvctemp.den.extractList)')), -1);

Two additional records to the TFMap table might help too:
-1, -1
0, 0
