### ISSUE TITLE
QVC.GetFieldValues breaks future QVC.CalendarFromField 

### ISSUE THREAD

**Issue by Aviaf47** [RobWunderlich/Qlikview-Components#46]
I had previously been using CalendarFromField on two separate fields, creating two separate calendars, with two sets of different prefixes for the calendar fields, which worked fine.

At a later point in time, I added a GetFieldValues call into the script before the CalendarFromField calls, on a separate field, and not using the same stem words. This ended up giving me an error when the script running gets to the CalendarFromField call, it tells me a table is not found when the script tries to drop it from a statement within the CalendarFromField call. If I comment out the two CalendarFromField calls, then the Get FieldValuescall works fine, and vice versa.

I created a blank new qvw to test this issue but cannot replicate it at this moment. Has anyone stumbled across this issue before?

I have attached a scrambled version of the qvw which would reload with either or the sets of calls commented out, but not with both of them being run, hopefully someone can find the issue. the GetFieldValues is on the main tab near bottom, and the two CalendarFromField calls are on the Calendar tab.

The scrambling will make some graphs not display properly.

Downlaod qvw here, it wouldn't let me attach: https://www.dropbox.com/s/p8xe20pyl1a6d49/MS%20Physician%20Scorecard%20-scrambled.qvw?dl=0

**Comment by RobWunderlich** [comment]
Can you post or link to the document log for a failing reload?

**Comment by Aviaf47** [comment]
I had fixed the issue by moving the calls around and continued to code. Now that I tried to switch them back to replicate the issue so I could post a failed log, it seems to be working fine. It must have been my mistake somewhere. Apologies!
