### ISSUE TITLE
vSetYTD not working as before

### ISSUE THREAD

**Issue by dajjan** [RobWunderlich/Qlikview-Components#55]
Hi, The Set variable for YTD and Rolling12 (maybe the others to) don´t listen to current selections anymore. Is this a feature or a bug? When I try to select a year older then current the YTD value still shows the last year in the calendar.

I also experience that I want YTD for the current year but when I for example have a calendar with stop 2017-12-31 it shows YTD for 2017. A work around for this is to stop the calander on today date.

Regards David

**Comment by RobWunderlich** [comment]
I can confirm that it's not working. I'll take a look tonight ans post a fix as soon as possible.

**Comment by dajjan** [comment]
When I try your qlikview example app it works until I reload, after that I have the same problem.
//David

**Comment by RobWunderlich** [comment]
I can't recreate. Are you using View or Sense? Can you post the document log?

**Comment by RobWunderlich** [comment]
Did you download the release file or are you including via http? I just updated the http file to v11.1, it was v11.

**Comment by dajjan** [comment]
Now it works, thanks!
