### ISSUE TITLE
Qvc.ColorTheme() remarks

### ISSUE THREAD

**Issue by KoenBal** [RobWunderlich/Qlikview-Components#60]
Hello Rob,

- I started to build my own ColorManagement Module as almost all suggested solutions on the community did not incorporate the idea of creating variables for independent frontend properties. But then I found the Qvc.ColorTheme() sub and I think you quite nailed it :). Though I have some questions/suggestions:

- I noticed that I receive all the color variables and not only the Qvc.Color.v.* color variables in the front end. I assume it is not the goal to have the vBlue, vDarkPurple, etc variables in the frontend as this is mentioned in the documentation '// Only ColorVariable names that begin with "Qvc.Color" will be propagated to the calling QVW.'

- I made some improvements to the ColorSample1.xlsm. The rgb or argb value and the visual color are now available on each line. This means you don't have to lookup a color manually when you are referencing variables. 
Now there is also only one input column for the user where he can input a color in 3 different ways:
Input can be:
-a reference to another ColorVariable
-a RGB or ARGB text value
-a background color
Adding colors using the QlikView color functions is not available anymore

I added a macro and some less elegant functions (I noticed excel is not QlikView) to get it working.

I hope you find it a step forward :).

,KR Koen

[ColorSample1.zip](https://github.com/RobWunderlich/Qlikview-Components/files/682345/ColorSample1.zip)

**Comment by RobWunderlich** [comment]
The doc comment "'// Only ColorVariable names that begin with "Qvc.Color" will be propagated to the calling QVW." in the xlsx file is in error.  All variables get loaded, but only Qvc.Color.v* names get loaded into the optional table -- if used.  It may be possible to not propagate the other variables, but that would be complex. If ther is a desire to have truly "temp" variables in this case, it would be better to name those variables something special like "Qvc.Color.temp.vxx" and then they could be explicitily deleted. 

I like the update to ColorSample1.xlsm, but I don't like the loss of being able to use the QV color functions.  If you like it the way it is, I could add it as a second sample so people could see both ways.

**Comment by KoenBal** [comment]
Hello Rob,

- I made a new version.
The Qlikview color functions can now still be used. But the 'Out color'column does not show a color for QV color functions or ARGB values.
- I added Temp.* variables which should only be used in the excel for referencing. These variables should not be read by the QvC.ColorTheme() SUB. I did not use Qvc.Color.temp.v.* because the color variable names get rather long and you only need to use them when referencing in the excel.
- Added colorbrewer color schemes (color schemes recommended by Stephen Few)
- Added guidelines.
- Made some layout changes.
- Added a variable category for color variables that are related to dashboard elements (ex. DropDownPanel, ButtonActive, ButtonInactive)

Any extra ideas?

,KR Koen

[ColorSample1_v3.zip](https://github.com/RobWunderlich/Qlikview-Components/files/685300/ColorSample1_v3.zip)
