### ISSUE TITLE
Using qvc.qvs - after CALL qvc.log, error visible on Qlik Sense

### ISSUE THREAD

**Issue by salurkar** [RobWunderlich/Qlikview-Components#67]
Hello Rob,

We are using qlikview components developed by yourslef.

While executing the load data using data load editor, we are receiving an errror

 "undefined: CALL >>>>>>Qvc.Log<<<<<<('>>> Incremental Load of AP Invoices All with inserts & updates')"

Please suggest what needs to be done.

Note : We are using Qlik Sense desk
![qlik error](https://user-images.githubusercontent.com/30053539/28030526-213bfbfa-6572-11e7-8cd4-223095418164.PNG)

**Comment by salurkar** [comment]
Issue resolved by adding the lines

SET _qvctemp.v.IncludeExtension=;
SET QvcLib='lib://Qlikview_AP';
$(Must_Include=$(QvcLib)\qvc_runtime\Qvc.qvs);
SET Qvc.Global.v.QlikProduct='SENSE';

**Comment by RobWunderlich** [comment]
What version of QVC?  I expected the QlikProduct issue was fixed in 11.1.

**Comment by salurkar** [comment]
I am using version 11.1 
Can see the lines in qvc.qvs file
(SET QVC.Gloval.V.Version = 11.1
LET Qvc.Gloval.V.QlikProduct = if(subfield(QlikViewVersion(),'.',1)>6,'VIEW','SENSE')))

Reviewing old issues saw statement SET _qvctemp.v.IncludeExtension=; SET and Qvc.Global.v.QlikProduct='SENSE'; was required and after adding the same, the load script worked fine.
