### ISSUE TITLE
Changing DateFormat affects qvc log file behavior

### ISSUE THREAD

**Issue by dgudmundsson** [RobWunderlich/Qlikview-Components#7]
After changing the DateFormat from the default 'M/D/YYYY' to 'D-MMM-YYYY' I noticed that the log file was not appending anymore. Perhaps not critical, but I generally use a more "international" D-MMM-YYYY date format to eliminate any D/M and M/D confusion in companies with US and non-US dashboard users.

From Qvc.qvs version 8.2.

Details:
Within SUB Qvc.Log, this is traced to the where clause that reads: "WHERE today(1) - Date#(subfield(@2,' ',2)) < $(Qvc.Log.v.KeepDays)"

**Comment by MattFryer** [comment]
Assuming this has been resolved and can be closed?
- Matt

**Comment by RobWunderlich** [comment]
No response, so assuming that setting TimeStamp works.
