### ISSUE TITLE
Syntax Error during DB extract with Qlik 12.2 Nov 2017 SR 2

### ISSUE THREAD

**Issue by Frogy76** [RobWunderlich/Qlikview-Components#73]
Hallo we upgraded yesterday our Qlik Environment from 11.2 to 12.2.

After the upgrade the QVC.DbExtract Method fails with the followin Syntax Error

Syntax error
Unknown statement: [app_aut_batch]: 		// vTablename is set by the IncrementalSetup routine.
REM
[app_aut_batch]: 		// vTablename is set by the IncrementalSetup routine.
REM

BR

Bastian

**Comment by RobWunderlich** [comment]
The problem is due to the new "BNF script mode" introduced in V12.  You can fix the problem by adding this as the **first** line of your script:

///$bnf off

**Comment by RobWunderlich** [comment]
///$bnf off
should be considered a workaround. I will make a code fix so $bnf off is not required.

**Comment by RobWunderlich** [comment]
Fixed in release v11.3.  ///$bnf off is no longer required.
