### ISSUE TITLE
CALL Qvc.GetFieldValues

### ISSUE THREAD

**Issue by GorumDerVan** [RobWunderlich/Qlikview-Components#85]
Hi Rob,
I added your calendar but it fails on the CALL Qvc.GetFieldValues.
This is the error:
CALL Qvc.GetFieldValues('_vStats', 'CanonicalDate')
Error: Script line error: 

The field CanonicalDate is present in the data, has data and in date format.

Is this dependend on a Sub Qvc.GetFieldValues? In that case, I have not located that Sub.

QlikView 11.20.12904.0 SR12 64-bit

Thank you very much!

**Comment by RobWunderlich** [comment]
Hello,
You must include the entire Qvc_Runtime/qvc.qvs.  It includes all the
dependent subs as well as initialization code.

Kind Regards,
Rob Wunderlich

http://MastersSummit.com   @QlikMasters
http://QlikviewCookbook.com   @QVCookbook
http://www.easyqlik.com  QViewer

**Comment by GorumDerVan** [comment]
Ok, I will do that. Thanks Rob!

**Comment by RobWunderlich** [comment]
Closed, usage error.
