### ISSUE TITLE
Add monthnr 

### ISSUE THREAD

**Issue by GorumDerVan** [RobWunderlich/Qlikview-Components#92]
HI Rob,
I added 
SET _fMonthnr='[$(_fieldPrefix)$(Qvc.Calendar.v.Field.Monthnr)]';
and
Num(Month(Date), '##')		as $(_fMonthnr),

in the qvc.qvs. The output is the month as a number which is exactly as needed.

However, the file name is only the _FieldPrefix (for instance 'Stars. ') part. 

I duplicate the part for _fMonth. Did I miss something? Thanks

**Comment by RobWunderlich** [comment]
Could you attach your entire qvc.qvs please.

**Comment by GorumDerVan** [comment]
[QVC.zip](https://github.com/RobWunderlich/Qlikview-Components/files/4393726/QVC.zip)

Hi Rob, added in Zip. Github doesn't accept qvs.

Regards
Michiel

**Comment by RobWunderlich** [comment]
Sorry for the delay, just noticed this in the inbox.  You need to assign a
name for your new field around line 109:

SET Qvc.Calendar.v.Field.Monthnr=MonthNum;

Kind Regards,
Rob Wunderlich
